from django.urls import path

from apps.persistence.views import (
    TenantAssetCatalogView,
    TenantBannerMaterialDetailView,
    TenantBannerMaterialListCreateView,
    TenantBootstrapView,
    TenantConfigurationView,
    TenantDestinationDetailView,
    TenantDestinationListCreateView,
    TenantPlatformConnectionDetailView,
    TenantPlatformConnectionDisconnectView,
    TenantPlatformConnectionImportView,
    TenantPlatformConnectionListView,
    TenantPlatformConnectionRefreshView,
    TenantSceneDetailView,
    FacebookEmbedCredentialsView,
    TenantSceneListCreateView,
    TenantTextMaterialCatalogView,
    TenantTickerMaterialDetailView,
    TenantTickerMaterialListCreateView,
    TwitchAuthorizeView,
    TwitchChatCredentialsView,
    TwitchOAuthCallbackView,
)

urlpatterns = [
    path('tenant', TenantBootstrapView.as_view(), name='tenant-bootstrap'),
    path(
        'tenant/<uuid:tenant_id>/configuration/',
        TenantConfigurationView.as_view(),
        name='tenant-configuration',
    ),
    path(
        'tenant/<uuid:tenant_id>/scenes/',
        TenantSceneListCreateView.as_view(),
        name='tenant-scenes',
    ),
    path(
        'tenant/<uuid:tenant_id>/scenes/<uuid:scene_id>/',
        TenantSceneDetailView.as_view(),
        name='tenant-scene-detail',
    ),
    path(
        'tenant/<uuid:tenant_id>/destinations/',
        TenantDestinationListCreateView.as_view(),
        name='tenant-destinations',
    ),
    path(
        'tenant/<uuid:tenant_id>/destinations/<uuid:destination_id>/',
        TenantDestinationDetailView.as_view(),
        name='tenant-destination-detail',
    ),
    path(
        'tenant/<uuid:tenant_id>/assets/',
        TenantAssetCatalogView.as_view(),
        name='tenant-assets',
    ),
    path(
        'tenant/<uuid:tenant_id>/text-materials/',
        TenantTextMaterialCatalogView.as_view(),
        name='tenant-text-materials',
    ),
    path(
        'tenant/<uuid:tenant_id>/banners/',
        TenantBannerMaterialListCreateView.as_view(),
        name='tenant-banners',
    ),
    path(
        'tenant/<uuid:tenant_id>/banners/<uuid:banner_id>/',
        TenantBannerMaterialDetailView.as_view(),
        name='tenant-banner-detail',
    ),
    path(
        'tenant/<uuid:tenant_id>/tickers/',
        TenantTickerMaterialListCreateView.as_view(),
        name='tenant-tickers',
    ),
    path(
        'tenant/<uuid:tenant_id>/tickers/<uuid:ticker_id>/',
        TenantTickerMaterialDetailView.as_view(),
        name='tenant-ticker-detail',
    ),
    path(
        'tenant/<uuid:tenant_id>/platform-connections/import/',
        TenantPlatformConnectionImportView.as_view(),
        name='tenant-platform-connection-import',
    ),
    path(
        'tenant/<uuid:tenant_id>/platform-connections/',
        TenantPlatformConnectionListView.as_view(),
        name='tenant-platform-connections',
    ),
    path(
        'tenant/<uuid:tenant_id>/platform-connections/<uuid:connection_id>/',
        TenantPlatformConnectionDetailView.as_view(),
        name='tenant-platform-connection-detail',
    ),
    path(
        'tenant/<uuid:tenant_id>/platform-connections/<uuid:connection_id>/disconnect/',
        TenantPlatformConnectionDisconnectView.as_view(),
        name='tenant-platform-connection-disconnect',
    ),
    path(
        'tenant/<uuid:tenant_id>/platform-connections/<uuid:connection_id>/refresh/',
        TenantPlatformConnectionRefreshView.as_view(),
        name='tenant-platform-connection-refresh',
    ),
    path(
        'tenant/<uuid:tenant_id>/platform-connections/<uuid:connection_id>/embed-credentials/',
        FacebookEmbedCredentialsView.as_view(),
        name='facebook-embed-credentials',
    ),
    path(
        'tenant/<uuid:tenant_id>/integrations/twitch/chat-credentials/',
        TwitchChatCredentialsView.as_view(),
        name='twitch-chat-credentials',
    ),
    path(
        'oauth/twitch/authorize/',
        TwitchAuthorizeView.as_view(),
        name='twitch-oauth-authorize',
    ),
    path(
        'oauth/twitch/callback/',
        TwitchOAuthCallbackView.as_view(),
        name='twitch-oauth-callback',
    ),
]
