# Generated by Django 5.0.1 on 2026-07-31 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('url', models.URLField(max_length=2048)),
                ('platform', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='persistence.tenant')),
            ],
            options={
                'db_table': 'tenant_destinations',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('scene_type', models.CharField(choices=[('CAMERA', 'Camera'), ('COUNTDOWN', 'Countdown')], max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('layout', models.CharField(blank=True, choices=[('CONTAIN', 'Contain'), ('COVER', 'Cover'), ('THUMBNAIL', 'Thumbnail'), ('GRID', 'Grid'), ('SIDE_BY_SIDE', 'Side by side'), ('HALFSCREEN', 'Half screen'), ('SPOTLIGHT', 'Spotlight'), ('CINEMA', 'Cinema'), ('PICTURE_IN_PICTURE', 'Picture in picture'), ('OVERLAY', 'Overlay'), ('FULLSCREEN', 'Fullscreen')], default='', max_length=32)),
                ('graphics_config', models.JSONField(blank=True, default=dict)),
                ('devices_config', models.JSONField(blank=True, default=dict)),
                ('sources_config', models.JSONField(blank=True, default=dict)),
                ('background_music_config', models.JSONField(blank=True, default=dict)),
                ('countdown_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countdown_target_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countdown_references', to='persistence.tenantscene')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='persistence.tenant')),
            ],
            options={
                'db_table': 'tenant_scenes',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='configuration', serialize=False, to='persistence.tenant')),
                ('layout', models.CharField(choices=[('CONTAIN', 'Contain'), ('COVER', 'Cover'), ('THUMBNAIL', 'Thumbnail'), ('GRID', 'Grid'), ('SIDE_BY_SIDE', 'Side by side'), ('HALFSCREEN', 'Half screen'), ('SPOTLIGHT', 'Spotlight'), ('CINEMA', 'Cinema'), ('PICTURE_IN_PICTURE', 'Picture in picture'), ('OVERLAY', 'Overlay'), ('FULLSCREEN', 'Fullscreen')], default='CONTAIN', max_length=32)),
                ('tile_order_config', models.JSONField(blank=True, default=dict)),
                ('devices_config', models.JSONField(blank=True, default=dict)),
                ('graphics_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.tenantscene')),
            ],
            options={
                'db_table': 'tenant_configurations',
            },
        ),
    ]
