# Generated by Django 5.0.1 on 2026-07-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdestination',
            name='url',
            field=models.CharField(max_length=2048),
        ),
    ]
