# Generated by Django 5.2.2 on 2026-08-01 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_alter_tenantdestination_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioMediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=2048)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=2048)),
                ('size', models.BigIntegerField(default=0)),
                ('media_format', models.CharField(default='image', max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('is_system_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='persistence.tenant')),
            ],
            options={
                'db_table': 'studio_media_assets',
                'ordering': ['asset_type', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'asset_type'], name='studio_medi_tenant__d70dcf_idx'), models.Index(fields=['asset_type', 'is_system_default'], name='studio_medi_asset_t_422fe7_idx')],
            },
        ),
    ]
