# Generated by Django 5.2.2 on 2026-08-01 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_studiomediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBannerMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('theme', models.CharField(default='classic', max_length=32)),
                ('primary', models.CharField(default='#111111', max_length=32)),
                ('secondary', models.CharField(default='#374151', max_length=32)),
                ('accent', models.CharField(default='#38bdf8', max_length=32)),
                ('font_size', models.PositiveSmallIntegerField(default=32)),
                ('is_display_names', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_materials', to='persistence.tenant')),
            ],
            options={
                'db_table': 'tenant_banner_materials',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenant_bann_tenant__246357_idx'), models.Index(fields=['is_system_default'], name='tenant_bann_is_syst_5f26c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantTickerMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('ticker_text', models.TextField(blank=True, default='')),
                ('ticker_position', models.CharField(default='bottom', max_length=16)),
                ('ticker_direction', models.CharField(default='rtl', max_length=8)),
                ('ticker_speed', models.FloatField(default=2.0)),
                ('primary', models.CharField(default='#111827', max_length=32)),
                ('secondary', models.CharField(default='#ffffff', max_length=32)),
                ('is_system_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticker_materials', to='persistence.tenant')),
            ],
            options={
                'db_table': 'tenant_ticker_materials',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenant_tick_tenant__cf039e_idx'), models.Index(fields=['is_system_default'], name='tenant_tick_is_syst_101988_idx')],
            },
        ),
    ]
