# Generated by Django 5.0.1 on 2026-08-01 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_tenantbannermaterial_tenanttickermaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('custom_rtmp', 'Custom RTMP')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('auth_expired', 'Auth Expired'), ('connecting', 'Connecting'), ('streaming', 'Streaming'), ('error', 'Error')], default='connecting', max_length=32)),
                ('platform_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('platform_login', models.CharField(blank=True, default='', max_length=128)),
                ('access_token_encrypted', models.TextField(blank=True, default='')),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('stream_key_encrypted', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_connections', to='persistence.tenantdestination')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='persistence.tenant')),
            ],
            options={
                'db_table': 'platform_connections',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'platform'], name='platform_co_tenant__36116f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='platformconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform'), name='unique_tenant_platform_connection'),
        ),
    ]
