# Generated by Django 5.2.2 on 2026-08-05 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_platform_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMusicTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=2048)),
                ('size', models.BigIntegerField(default=0)),
                ('is_system_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_tracks', to='persistence.tenant')),
            ],
            options={
                'db_table': 'tenant_music_tracks',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenant_musi_tenant__baeddb_idx'), models.Index(fields=['is_system_default'], name='tenant_musi_is_syst_bf6de5_idx')],
            },
        ),
    ]
